name: Build code

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/zephyrproject-rtos/ci:main
    steps:
      - name: Apply container owner mismatch workaround
        run: |
          # FIXME: The owner UID of the GITHUB_WORKSPACE directory may not
          #        match the container user UID because of the way GitHub
          #        Actions runner is implemented. Remove this workaround when
          #        GitHub comes up with a fundamental fix for this problem.
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - uses: actions/checkout@v4
        with:
          path: workspace/app
      - uses: actions/cache@v4
        with:
          path: |
            workspace/bootloader
            workspace/modules
            workspace/tools
            workspace/zephyr
          key: ${{ runner.os }}-${{ hashFiles('workspace/app/west.yml') }}
      - working-directory: workspace
        run: |
          west init --local app
          west update
          west zephyr-export
          export ZEPHYR_SDK_INSTALL_DIR="/opt/toolchains/zephyr-sdk-$( cat zephyr/SDK_VERSION )"
          west build -b qemu_x86 -s app
        
